version: '3.7'

services:
  dynamodb:
    image: 'amazon/dynamodb-local'
    ports:
      - 8000:8000
    command: ['-jar', 'DynamoDBLocal.jar', '-sharedDb']
    tty: true # Colorised Terminal Output

  api:
    build:
      context: .
      target: debug
    depends_on:
      - dynamodb
    ports:
      - 5000:5000 # Expose Lambda HTTP Port
      - 5858:5858 # Nodejs Debug Port
    volumes:
      - .:/app # Live Reload
      - /app/node_modules # Prevents node_modules being overwritten by host directory
    environment:
      DYNAMODB_HOST: dynamodb
      DYNAMODB_PORT: 8000
      DYNAMODB_NO_START: 'true'
    env_file: .env # SERVERLESS_ACCESS_KEY
    command: 'node --inspect=0.0.0.0:5858 --nolazy node_modules/.bin/serverless offline --webpack-use-polling'
    tty: true # Colorised Terminal Output
