version: '3.7'

services:
  dynamodb:
    image: 'amazon/dynamodb-local'
    ports:
      - 8000:8000
    expose:
      - 8000
    command: ['-jar', 'DynamoDBLocal.jar', '-sharedDb']

  api:
    build: .
    depends_on:
      - dynamodb
    links:
      - dynamodb
    ports:
      - 5000:5000 # Expose Lambda HTTP Port
    volumes:
      - .:/app # Live Reload
      - /app/node_modules # Prevents node_modules being overwritten by host directory
    environment:
      DYNAMODB_HOST: dynamodb
      DYNAMODB_PORT: 8000
      DYNAMODB_NO_START: 'true'
    env_file: .env.dev # SERVERLESS_ACCESS_KEY
    command: ['serverless', 'offline', '--host', '0.0.0.0'] # Add host to prevent socket hang up
    tty: true # Colorised Terminal Output
