service: 'serverless-test'

app: 'typescript-lambda-dynamodb-app'
org: 'jimmeex'

frameworkVersion: '2'

provider:
  name: 'aws'
  runtime: 'nodejs12.x'
  region: "${env:AWS_REGION, 'ap-southeast-2'}"
  stage: "${opt:stage, 'dev'}"
  environment:
    tableName: '${self:service}-${self:custom.tableName}-${self:provider.stage}'

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dynamodb-local

custom:
  tableName: 'cool-places'
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true
  serverless-offline:
    host: '0.0.0.0'
    httpPort: 5000
  dynamodb:
    stages:
      - dev
    start:
      port: '${env:DYNAMODB_PORT, 8000}'
      host: '${env:DYNAMODB_HOST, localhost}'
      noStart: '${env:DYNAMODB_NO_START, false}'
      migrate: true

functions:
  hello:
    handler: 'src/lambdas/endpoints/sendHello.handler'
    events:
      - http:
          path: 'send-hello'
          method: 'get'
  create:
    handler: 'src/lambdas/endpoints/createPlace.handler'
    events:
      - http:
          path: 'create-place'
          method: 'post'

resources:
  Resources:
    CoolPlaces:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: '${self:service}-${self:custom.tableName}-${self:provider.stage}'
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'id'
            KeyType: 'HASH'
        BillingMode: 'PAY_PER_REQUEST'
